// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserManagementService.Data;

#nullable disable

namespace UserManagementService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250429061223_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserManagementService.Models.PermissionModel", b =>
                {
                    b.Property<int>("id_permission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_permission"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("permission_name")
                        .HasColumnType("text");

                    b.HasKey("id_permission");

                    b.ToTable("permissions", "dbo");
                });

            modelBuilder.Entity("UserManagementService.Models.RoleModel", b =>
                {
                    b.Property<int>("id_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_role");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_role"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name_role")
                        .HasColumnType("text")
                        .HasColumnName("name_role");

                    b.HasKey("id_role");

                    b.ToTable("role", "dbo");
                });

            modelBuilder.Entity("UserManagementService.Models.RolePermissionModel", b =>
                {
                    b.Property<int>("id_role_permission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_role_permission"));

                    b.Property<int?>("id_permission")
                        .HasColumnType("integer");

                    b.Property<int?>("id_role")
                        .HasColumnType("integer");

                    b.HasKey("id_role_permission");

                    b.HasIndex("id_permission");

                    b.HasIndex("id_role");

                    b.ToTable("role_permission", "dbo");
                });

            modelBuilder.Entity("UserManagementService.Models.UserModel", b =>
                {
                    b.Property<string>("id_user")
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<int?>("id_role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<int?>("status")
                        .HasColumnType("integer");

                    b.HasKey("id_user");

                    b.HasIndex("id_role");

                    b.ToTable("user", "dbo");
                });

            modelBuilder.Entity("UserManagementService.Models.RolePermissionModel", b =>
                {
                    b.HasOne("UserManagementService.Models.PermissionModel", "permission")
                        .WithMany()
                        .HasForeignKey("id_permission");

                    b.HasOne("UserManagementService.Models.RoleModel", "role")
                        .WithMany()
                        .HasForeignKey("id_role");

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("UserManagementService.Models.UserModel", b =>
                {
                    b.HasOne("UserManagementService.Models.RoleModel", "role")
                        .WithMany()
                        .HasForeignKey("id_role");

                    b.Navigation("role");
                });
#pragma warning restore 612, 618
        }
    }
}
